spring:
  application:
    name: FOOD-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/microservices_db
    username: "{cipher}be09066b095849cfe4d5fc86087d4edceac917fdff8cde18a38cf2018662c900"
    password: "{cipher}be09066b095849cfe4d5fc86087d4edceac917fdff8cde18a38cf2018662c900"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# eureka configuration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: true


management:
  endpoint:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true
