spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db?options=-c%20TimeZone=UTC
spring.datasource.username=user
spring.datasource.password="{cipher}9c99646664fd0a28e06483cafb9e8147f182f39b9bea35d23f3f9e05f39a6fdf"

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

info.app.name=restaurant-service
info.app.description=This is restaurant service development env.
info.app.version=1.0 Development

