spring.application.name=user-service
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/microservices_db
spring.datasource.username="{cipher}be09066b095849cfe4d5fc86087d4edceac917fdff8cde18a38cf2018662c900"
spring.datasource.password="{cipher}be09066b095849cfe4d5fc86087d4edceac917fdff8cde18a38cf2018662c900"

#eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


